version: '3'

services:
    dbapp:
        image: mysql:5
        container_name: moodleDB_setName
        restart: on-failure
        volumes:
            - db-volume:/var/lib/mysql
            - ./dbDump.sql:/docker-entrypoint-initdb.d/dbDump.sql
            - ./newDump.sql:/tmp/newDump.sql
        env_file:
            - moodle_variables.env
        networks:
            - backendDB
        deploy:
            replicas: 1
            restart_policy:
                condition: on-failure
    moodleapp:
        image: jhardison/moodle:latest
        container_name: moodleApp_setName
        links:
            - dbapp:DB
        depends_on:
            - dbapp
        restart: on-failure
        volumes:
            - moodleapp-data:/var/moodledata
            - ./foreground.sh:/etc/apache2/foreground.sh
            - ./moodle-config.php:/var/www/html/config.php
            - ./moodle-files/moodle:/var/www/html
            - ./logs/error.log:/var/log/apache2/error.log
            - ./logs/access.log:/var/log/apache2/access.log
        ports:
            - 80:80
            - 443:443
        env_file:
            - moodle_variables.env
        networks:
            - backendDB
            - frontendWEB
        deploy:
            replicas: 1
            restart_policy:
                condition: on-failure

volumes:
    db-volume:
    moodleapp-data:

networks:
    backendDB:
    frontendWEB:
